# Nombre del flujo de trabajo que verás en GitHub
name: Compilar APK con Buildozer

# Disparadores: Cuándo se debe ejecutar esta acción
on:
  # 1. Cada vez que subes código a la rama "main" o "master"
  push:
    branches: [ "main", "master" ]
    
  # 2. Te permite ejecutarlo manualmente desde la pestaña "Actions" en GitHub
  workflow_dispatch:

# Tareas a realizar
jobs:
  build:
    # La máquina virtual que usará GitHub para compilar (Ubuntu más reciente)
    runs-on: ubuntu-latest

    # Secuencia de pasos a seguir
    steps:
      # Paso 1: Descargar tu código desde tu repositorio a la máquina virtual
      - name: Descargando el repositorio
        uses: actions/checkout@v4

      # --- PASO AÑADIDO PARA EL CACHÉ ---
      # Este paso intenta restaurar el caché de Buildozer de una ejecución anterior.
      # Si lo encuentra, las descargas del SDK/NDK serán casi instantáneas.
      - name: Cache de las dependencias de Buildozer
        uses: actions/cache@v4
        with:
          # La carpeta que queremos guardar y restaurar
          path: ~/.buildozer
          # Una "llave" única para identificar este caché. 
          # Si el archivo buildozer.spec cambia, la llave cambia y se crea un caché nuevo.
          key: ${{ runner.os }}-buildozer-v1-${{ hashFiles('buildozer.spec') }}
          # Una llave de restauración por si no hay una coincidencia exacta.
          restore-keys: |
            ${{ runner.os }}-buildozer-v1-

      # Paso 3: Ejecutar la acción de Buildozer
      - name: Compilar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer # Le damos un ID a este paso para poder referenciarlo después
        with:
          # El comando que se ejecutará.
          command: buildozer android debug

      # Paso 4: Subir el APK generado como un "artefacto"
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          # El nombre que tendrá el paquete descargable
          name: mi-apk
          # La ruta donde se encuentra el APK generado.
          path: ${{ steps.buildozer.outputs.filename }}
